version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g jest
  pre_build:
    commands:
      - echo Build start
  build:
    commands:
      - jest
  post_build:
    commands:
      - echo Build completed